export const dummyApi = {
  doctors: [
    {
      id: 1,
      firstName: "Willy",
      lastName: "Wonka",
      username: "willy1",
      speciality: "Gynecologist",
      gender: "Male",
      patientsAppointed: [2, 3, 5],
      address: "795 Folsom Ave, Suite 600 San Francisco, CADGE 94107",
      profilePic: null,
    },
    {
      id: 2,
      firstName: "Joe",
      lastName: "Roots",
      username: "joe1",
      speciality: "Dermatologist",
      gender: "Male",
      patientsAppointed: [2, 3, 5],
      address: "795 Folsom Ave, Suite 600 San Francisco, CADGE 94107",
      profilePic: null,
    },
    {
      id: 3,
      firstName: "Jane",
      lastName: "Foster",
      username: "jane1",
      speciality: "Dermatologist",
      gender: "Female",
      patientsAppointed: [2, 3, 5],
      address: "795 Folsom Ave, Suite 600 San Francisco, CADGE 94107",
      profilePic: null,
    },
    {
      id: 4,
      firstName: "Will",
      lastName: "Smith",
      username: "will1",
      speciality: "Gynecologist",
      gender: "Male",
      patientsAppointed: [2, 3, 5],
      address: "795 Folsom Ave, Suite 600 San Francisco, CADGE 94107",
      profilePic: null,
    },
  ],
  patients: [
    {
      id: 1,
      fullName: "Liam",
      age: 42,
      phone: "9097785207",
      gender: "Male",
      doctorsAppointed: [4, 7, 8],
      address: "71 Pilgrim Avenue Chevy Chase, MD 20815",
      lastVisited: "19-09-2018",
      status: "approved",
      profilePic: null,
    },
  ],
  appointments: [
    {
      id: 1,
      patientId: 1,
      doctorId: 1,
      patientName: "Liam",
      doctorName: "Dr. Willy Wonka",
      patientEmail: "liam@gmail.com",
      appointmentDate: "18-12-2021",
      appointmentTime: { from: "09:30", to: "10:12" },
      patientNumber: "1111111111",
      patientCondition: "allergy",
      patientImage: null,
    },
  ],
  billings: [
    {
      id: 1,
      patientId: 1,
      patientName: "Liam",
      doctorId: 1,
      doctorName: "Dr. Willy Wonka",
      date: "19-09-2018",
      items: [
        { id: 1, name: "Diagosis", quantity: 1, cost: 5 },
        { id: 2, name: "Med1", quantity: 1, cost: 5 },
        { id: 3, name: "Med2", quantity: 1, cost: 5 },
      ],
      tax: 10,
      discount: 2,
      paymentMethod: "UPI",
      transactionId: 1,
      paid: true,
    },
  ],
};
